app:
  name: "ZDax"
  manager_ip: "192.168.1.5"
  domain: "test.local"
  subdomain: "www"
ssl:
  enabled: false
  email: "business@zsmart.tech"
image:
  barong: gcr.io/zsmartex/barong:2.4.0
  peatio: gcr.io/zsmartex/peatio:2.4.0
  postmaster: gcr.io/zsmartex/postmaster:2.0.0
  z-maker: gcr.io/zsmartex/z-maker:1.0.0
storage:
  provider: "Google"
  bucketName: "zsmart"
  accessKey: "GOOGTQRI3JKKSPRV4XBKNPKZ"
  secretKey: "xoaBinmXXTV+E6J/dceV+60yY62kOHW/EKDZYdad"
terraform:
  credentials: "~/safe/zdax.json"
  project: "example-zdax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "zdax-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+18577635282"
  account_sid: "AC9842e4cc2cfd0f21f93c7475f6d4723b"
  auth_token: "f3d3bc96dea477cf8a855608b1eb5951"
vault:
  url: http://vault:8200
  token: s.Syal4b4mXnHB8j5Uky5dJKjC
recaptcha:
  siteKey: 6LcrA5wUAAAAABY8KW-beaUOjShGC_U2va3kJEJt
  secretKey: 6LcrA5wUAAAAAK53t5qrkC7wvMB1tBeJed2YEkMI
daemons:
  withdraw_audit: false
  blockchain: false
  global_state: true
  deposit_collection: false
  deposit_collection_fees: false
  deposit_coin_address: false
  market_ticker: true
  matching: true
  slave_book: true
  order_processor: true
  trade_executor: true
  withdraw_coin: false
  k: true
  influx_writer: true
sendgrid_api_key: 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
