---
app:
  name: Z-Dax
  domain: zsmartex.io
  subdomain: www
render_protect: false
ssl:
  enabled: true
images:
  barong: zsmartex/barong
  peatio: zsmartex/peatio
  rango: zsmartex/rango
  kouda: zsmartex/kouda
  quantex: zsmartex/quantex
  coverapp: zsmartex/coverapp
  castle: zsmartex/castle
  mobiapp: zsmartex/mobiapp:dev
  mailer: zsmartex/mailer
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.KJcTVhs76z9dEnf98DsFnHy4
  peatio_token: s.6KoBxS4PBg4tZbZzofcSctJv
  peatio_crypto_token: s.uQNB7EZiRNQoEwOytBYXg8vo
  barong_token: s.2XapJXXzMoWJhSQmx3os5jOB
  quantex_token: s.W2Vze3bC80G5S5FsWrLLv2jD
  quantex_runner_token: s.VaVIB2eoElI7GcV35T3vere9
database:
  host: db
  port: 5432
  user: zsmartex
  password: zsmartex
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.zoho.com
  port: 587
  user: admin@coincooper.com
  password: NgEX9b23xmry
  sender_email: admin@coincooper.com
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  deposit: true
  blockchain: true
  deposit_address: true
  withdraw: true
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
  peatio_system_notify: true
  barong_system_notify: true
  code: true
  peatio_grpc: true
  p2p: true
  conversation: true
  notify: true
  activity_recorder: true
